export const ACTION_NAME = 'ACTION_NAME';
export const RESET_COUNTER = 'RESET_COUNTER';
export const ADD_COUNTER = 'ADD_COUNTER';
export const SUB_COUNTER = 'SUB_COUNTER';
export const FIBONACI_NEXT = 'FIBONACI_NEXT';
export const FIBONACI_PREV = 'FIBONACI_PREV';